<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "translation"
 *
 * Auto generated by Extension Builder 2018-02-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'translation',
    'description' => 'Translation database',
    'category' => 'plugin',
    'author' => 'Alex Kellne',
    'author_email' => 'alexander.kellner@in2code.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
